version: "2.1"
services:
  consul1:
    image: hashicorp/consul:latest
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0"
  consul2:
    image: hashicorp/consul:latest
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -retry-join consul1 -disable-host-node-id"
    depends_on:
      - consul1
  consul3:
    image: hashicorp/consul:latest
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -retry-join consul1 -disable-host-node-id"
    depends_on:
      - consul1

  vtctld:
    image: vitess/lite:v20.0.1
    ports:
      - "15000:$WEB_PORT"
      - "15999:$GRPC_PORT"
    command: ["sh", "-c", " /vt/bin/vtctld \
        $TOPOLOGY_FLAGS \
        --cell $CELL \
        --service_map 'grpc-vtctl,grpc-vtctld' \
        --backup_storage_implementation file \
        --file_backup_storage_root /vt/vtdataroot/backups \
        --logtostderr=true \
        --port $WEB_PORT \
        --grpc_max_message_size 104857600 \
        --grpc_port $GRPC_PORT
        "]
    depends_on:
      consul1:
        condition: service_started
      consul2:
        condition: service_started
      consul3:
        condition: service_started
#      external_db_host:
#        condition: service_healthy

  vtgate:
    image: vitess/lite:v20.0.1
    ports:
      - "15099:$WEB_PORT"
      - "15991:$GRPC_PORT"
      - "15306:$MYSQL_PORT"
    command: ["sh", "-c", "/vt/bin/vtgate \
        $TOPOLOGY_FLAGS \
        --logtostderr=true \
        --port $WEB_PORT \
        --grpc_port $GRPC_PORT \
        --mysql_server_port $MYSQL_PORT \
        --mysql_auth_server_impl none \
        --cell $CELL \
        --cells_to_watch $CELL \
        --tablet_types_to_wait PRIMARY,REPLICA \
        --service_map 'grpc-vtgateservice' \
        --enable-views \
        --enable_system_settings=true \
        --max_memory_rows 1000000 \
        --grpc_max_message_size 104857600 \
        "]
    volumes:
      - ".:/script"
#    environment:
#      - KEYSPACE=customer
#      - DB
    depends_on:
      vtctld:
        condition: service_started
      vttablet101:
        condition: service_healthy

  schemaload:
    image: vitess/lite:v20.0.1
    command:
    - sh
    - -c
    - /script/schemaload.sh
    environment:
    - TOPOLOGY_FLAGS
    - WEB_PORT
    - GRPC_PORT
    - CELL
    - KEYSPACE
    - TARGETTAB
    - SLEEPTIME
    - VSCHEMA_FILE
    - SCHEMA_FILES
    - POST_LOAD_FILE
    - EXTERNAL_DB
    volumes:
    - .:/script
    depends_on:
      vttablet101:
        condition: service_healthy

  set_keyspace_durability_policy:
    command:
      - sh
      - -c
      - /script/set_keyspace_durability_policy.sh
    depends_on:
      - vttablet101
    environment:
      - KEYSPACES=commerce customer
      - GRPC_PORT=15999
    image: vitess/lite:v20.0.1
    volumes:
      - .:/script

  vttablet101:
    image: vitess/lite:v20.0.1
    ports:
      - "15101:15101"
      - "$GRPC_PORT"
      - "3306"
    volumes:
      - ".:/script"
      - "./backups:/vt/vtdataroot/backups"
      - "vttablet101-data:/vt/vtdataroot"
    environment:
      - TOPOLOGY_FLAGS
      - WEB_PORT
      - GRPC_PORT
      - CELL
      - KEYSPACE
      - DB
      - EXTERNAL_DB
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_CHARSET
      - ROLE=primary
    command: ["sh", "-c", "/script/vttablet-up.sh 101"]
    depends_on:
      - vtctld
    healthcheck:
      test: ["CMD-SHELL","curl -s --fail --show-error localhost:15101/debug/health"]
      interval: 30s
      timeout: 10s
      retries: 15

  vttablet102:
    image: vitess/lite:v20.0.1
    ports:
      - "15102:15102"
      - "$GRPC_PORT"
      - "3306"
    volumes:
      - ".:/script"
      - "./backups:/vt/vtdataroot/backups"
      - "vttablet102-data:/vt/vtdataroot"
    environment:
      - TOPOLOGY_FLAGS
      - WEB_PORT
      - GRPC_PORT
      - CELL
      - KEYSPACE
      - DB
      - EXTERNAL_DB
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_CHARSET
    command: ["sh", "-c", "/script/vttablet-up.sh 102"]
    depends_on:
      vtctld:
        condition: service_started
      vttablet101:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl -s --fail --show-error localhost:15102/debug/health"]
      interval: 30s
      timeout: 10s
      retries: 15

  vttablet103:
    image: vitess/lite:v20.0.1
    ports:
      - "15103:15103"
      - "$GRPC_PORT"
      - "3306"
    volumes:
      - ".:/script"
      - "./backups:/vt/vtdataroot/backups"
      - "vttablet103-data:/vt/vtdataroot"
    environment:
      - TOPOLOGY_FLAGS
      - WEB_PORT
      - GRPC_PORT
      - CELL
      - KEYSPACE
      - DB
      - EXTERNAL_DB
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_CHARSET
    command: ["sh", "-c", "/script/vttablet-up.sh 103"]
    depends_on:
      vtctld:
        condition: service_started
      vttablet102:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl -s --fail --show-error localhost:15103/debug/health"]
      interval: 30s
      timeout: 10s
      retries: 15

  vttablet201:
    image: vitess/lite:v20.0.1
    ports:
      - "15201:15201"
      - "$GRPC_PORT"
      - "3306"
    volumes:
      - ".:/script"
      - "./backups:/vt/vtdataroot/backups"
      - "vttablet201-data:/vt/vtdataroot"
    environment:
      - TOPOLOGY_FLAGS
      - WEB_PORT
      - GRPC_PORT
      - CELL
      - KEYSPACE=customer
      - DB
      - EXTERNAL_DB
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_CHARSET
      - ROLE=primary
    command: ["sh", "-c", "/script/vttablet-up.sh 201"]
    depends_on:
      - vtctld
    healthcheck:
      test: ["CMD-SHELL","curl -s --fail --show-error localhost:15201/debug/health"]
      interval: 30s
      timeout: 10s
      retries: 15

  vtorc:
    image: vitess/lite:v20.0.1
    command: ["sh", "-c", "/script/vtorc-up.sh"]
    depends_on:
      - vtctld
      - set_keyspace_durability_policy
    ports:
      - "13000:8080"
    volumes:
      - ".:/script"
    environment:
      - WEB_PORT=8080
      - TOPOLOGY_FLAGS
      - WEB_PORT
      - GRPC_PORT
      - CELL
#      - KEYSPACE=customer
      - DB
      - EXTERNAL_DB
      - DB_PORT
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_CHARSET
    healthcheck:
      test: ["CMD-SHELL","curl -s --fail --show-error localhost:8080/debug/health"]
      interval: 5s
      timeout: 10s
      retries: 15

volumes:
  vttablet101-data:
  vttablet102-data:
  vttablet103-data:
  vttablet201-data:
